### ISSUE TITLE
Repack client

### ISSUE THREAD

**Issue by tr0y96** [x1nixmzeng/z3ResEx#2]
Hello

i want to repack the client after unpack it
it is possible?

**Comment by x1nixmzeng** [comment]
Hi, thanks for your comment!

I don't think repacking is possible due to the ECC method which relies on a private key to encrypt the data. It may be possible to re-inject modifications, although this is beyond the scope of the z3ResEx project.

**Comment by raiderz** [comment]
Hi! Maybe you help me? Raiderz have no russian language. =( I want to unpack -> some translate -> and repack. Can i do it?

**Comment by x1nixmzeng** [comment]
Hi, thanks for your comment!

As mentioned above, repacking goes beyond the scope of the z3ResEx project. There is a Russian server online however, although I've not tested it yet.

**Comment by raiderz** [comment]
Unfortunately, there is no official Russian server... There is a pirate server that translated only interface and little more.

**Comment by raiderz** [comment]
So you can't do it? Maybe just for me (for small reward of course). Because I really want to play Raiderz with my guild and my const party, but half of them don't know english. And we all want Russian's localisation.

**Comment by x1nixmzeng** [comment]
I don't intend to work on repacking the filesystem. Once the game starts to check for modified local files the means of evading their protection would require constant attention.
