### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ghost** [x1nixmzeng/z3ResEx#5]
Could you make it possible to get a compiler for GunZ2? I'm not going to make hacks or anything with it, but since GunZ2 is open for suggestions + they implant new sets, but I need to test these sets in-game first, that's why I would like to have a compiler.

**Comment by x1nixmzeng** [comment]
Hello

Extracting files is only possible because the key used to decrypt the data is embedded into the game.

It is not possible to repack the files using the same key due to the nature of public-key encryption. This private key also varies between publishers.
